### ISSUE TITLE
[BUG] Newest Version isn't downloadeable on V10

### ISSUE THREAD

**Issue by cadowtin** [p4535992/foundryvtt-inventory-plus#7]
```
setup.js:292 Error: module inventory-plus version 0.5.22 requires an older version of 
      the Foundry Virtual Tabletop software: 9 or older
    at Module.installPackage (/home/ubuntu/foundry/resources/app/dist/packages/views.mjs:1:1882)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async SetupView.handlePost (/home/ubuntu/foundry/resources/app/dist/server/views/setup.mjs:1:1980)
```

**Comment by jalspaugh3** [comment]
Any ETA on this?  Our game really relies on it!

**Comment by p4535992** [comment]
this week end i was busy with others module, maybe the next week i'll find the time.
